// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWgrBBbWuEGNG2Ls8W8V2G71zws_nvf8M',
    appId: '1:176585647678:web:df6caa89c5a63e9ca2d36f',
    messagingSenderId: '176585647678',
    projectId: 'shopthuongmai-5c07f',
    authDomain: 'shopthuongmai-5c07f.firebaseapp.com',
    storageBucket: 'shopthuongmai-5c07f.firebasestorage.app',
    measurementId: 'G-T0JVXWFZDQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUTAEw7lgFNTdCWxQONEA36YTuhzJhfiY',
    appId: '1:176585647678:android:890b945fc4c6d39fa2d36f',
    messagingSenderId: '176585647678',
    projectId: 'shopthuongmai-5c07f',
    storageBucket: 'shopthuongmai-5c07f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKZiXcg9QydaXbXlwuCo9gJYMTCjhQKk4',
    appId: '1:176585647678:ios:d224a74cbff91044a2d36f',
    messagingSenderId: '176585647678',
    projectId: 'shopthuongmai-5c07f',
    storageBucket: 'shopthuongmai-5c07f.firebasestorage.app',
    iosBundleId: 'com.example.thuongmaidientu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKZiXcg9QydaXbXlwuCo9gJYMTCjhQKk4',
    appId: '1:176585647678:ios:d224a74cbff91044a2d36f',
    messagingSenderId: '176585647678',
    projectId: 'shopthuongmai-5c07f',
    storageBucket: 'shopthuongmai-5c07f.firebasestorage.app',
    iosBundleId: 'com.example.thuongmaidientu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWgrBBbWuEGNG2Ls8W8V2G71zws_nvf8M',
    appId: '1:176585647678:web:39f65d033c9fad5fa2d36f',
    messagingSenderId: '176585647678',
    projectId: 'shopthuongmai-5c07f',
    authDomain: 'shopthuongmai-5c07f.firebaseapp.com',
    storageBucket: 'shopthuongmai-5c07f.firebasestorage.app',
    measurementId: 'G-5C9BGL2MTM',
  );
}
